### ISSUE TITLE
Problem with LASSCF([1, 1], [1, 1])

### ISSUE THREAD

**Issue by ruthenium96** [MatthewRHermes/mrh#11]
Hello again!

I guess, I found an error. Could you please help me?
I tried to calculate energy difference between singlet and triplet states spanned by interaction of cation-radical and anion-radical using vLASSCF. It is looking like broken symmetry (1, 1) approach, but in this case BS produces an error due to charge transfer. I hoped that SA-vLASSCF `charges` would help me to avoid charge transfer, but catch the error.
My Python code:

```
import numpy as np
from pyscf import gto
from pyscf import lib
from pyscf.tools import molden
from pyscf import scf, mcscf

from scipy import linalg
from mrh.my_pyscf.fci import csf_solver
from mrh.my_pyscf.mcscf.lasscf_testing import LASSCF
from mrh.my_pyscf.mcscf import lassi

lib.num_threads(16)

CA = gto.Mole()
CA.verbose = 4
CA.spin = 2
CA.charge = 0
CA.basis = 'ccpvdz'
CA.max_memory = 30000 #MB
CA.symmetry = False
CA.atom = '''Cr1       7.911000000      7.617500000      0.000000000
C1        5.894011000      6.872508000      0.085544000
C1        6.748689000      5.854049000     -0.411035000
C1        7.917265000      5.505929000      0.304442000
C1        8.216340000      6.151131000      1.530605000
C1        7.355230000      7.155880000      2.027856000
C1        6.195699000      7.528375000      1.299839000
H1        6.591147000      5.454130000     -1.245086000
H1        5.199044000      7.183302000     -0.422120000
H1        5.688987000      8.226900000      1.591068000
H1        7.596488000      7.647970000      2.821599000
H1        9.018685000      5.979737000      1.957204000
H1        8.534590000      4.958992000     -0.042548000
C1        9.927989000      8.362491000     -0.085544000
C1        9.073311000      9.380951000      0.411035000
C1        7.904735000      9.729071000     -0.304442000
C1        7.605660000      9.083869000     -1.530605000
C1        8.466770000      8.079121000     -2.027856000
C1        9.626301000      7.706625000     -1.299839000
H1        9.230853000      9.780870000      1.245086000
H1       10.622956000      8.051697000      0.422120000
H1       10.133013000      7.008100000     -1.591068000
H1        8.225512000      7.587030000     -2.821599000
H1        6.803315000      9.255262000     -1.957204000
H1        7.287410000     10.276007000      0.042548000
S2       4.043083000      4.369093000      2.200287000
N2        3.276583000      5.143336000      0.949154000
N2        4.733290000      3.074423000      1.411023000
C2        3.543998000      4.390727000     -0.127980000
S2       3.867917000      3.248407000     -2.200287000
N2        4.634417000      2.474164000     -0.949154000
N2        3.177710000      4.543077000     -1.411023000
C2        4.367002000      3.226773000      0.127980000
'''
CA.build()

CA_rohf = scf.ROHF(CA)
CA_rohf.level_shift = 0.3
CA_rohf.kernel()

CA_salas = LASSCF (CA_rohf, (1, 1), (1, 1))
CA_salas = CA_salas.state_average (np.ones(2) / 2,
    spins=[[1, 1], [1, -1]],
    smults=[[2, 2], [2, 2]],
    charges=[[1, -1], [1, -1]])
mo_loc = CA_salas.localize_init_guess ((list (range (25)), list (range (25, 33))), CA_rohf.mo_coeff)
CA_salas.kernel (mo_loc)
print ("\n---SA-LASSCF---")
print ("Energy:", CA_salas.e_states)
```
stderr:
```
Traceback (most recent call last):
  File "CA_salas.py", line 108, in <module>
    CA_salas.kernel (mo_loc)
  File "path_to_mrh/mrh/my_pyscf/mcscf/lasci.py", line 1268, in kernel
    kernel(self, mo_coeff, ci0=ci0, verbose=verbose, casdm0_fr=casdm0_fr, conv_tol_grad=conv_tol_grad)
  File "path_to_mrh/mrh/my_pyscf/mcscf/lasci.py", line 801, in kernel
    ci0 = get_init_guess_ci (las, mo_coeff, h2eff_sub)
  File "path_to_mrh/mrh/my_pyscf/mcscf/lasci.py", line 1100, in get_init_guess_ci
    hdiag_csf = solver.make_hdiag_csf (h1e, eri, norb, nelec)
  File "path_to_mrh/mrh/my_pyscf/fci/csf.py", line 479, in make_hdiag_csf
    return make_hdiag_csf (h1e, eri, norb, nelec, self.transformer, hdiag_det=hdiag_det)
  File "path_to_mrh/mrh/my_pyscf/fci/csf.py", line 71, in make_hdiag_csf
    hdiag_det = make_hdiag_det (None, h1e, eri, norb, nelec)
  File "path_to_mrh/mrh/my_pyscf/fci/csf.py", line 66, in make_hdiag_det
    return direct_uhf.make_hdiag (unpack_h1e_ab (h1e), [eri, eri, eri], norb, nelec)
  File "path_to_pyscf/pyscf/fci/direct_uhf.py", line 135, in make_hdiag
    occslstb = cistring._gen_occslst(range(norb), nelecb)
  File "path_to_pyscf/pyscf/fci/cistring.py", line 75, in _gen_occslst
    assert(nelec >= 0)
AssertionError
```
I'll be grateful for any advice!

**Comment by MatthewRHermes** [comment]
It looks like you are trying to state-average two closed-shell states, |0>^|2> and |2>^|0>, which are basically just two single determinants, |02> and |20>. Is this right? If not, the issue might be a misunderstanding of how the "charges" kwarg works. To be clear, the "charges" kwarg modifies the number of electrons relative to what the user specifies when building the LASSCF object, not relative to the valence of some atom.

If this is what you intended, then the problem is just that I never implemented the edge case logic for zero electrons in an active subspace; i.e., states like |0...0>. It'll probably also crash on the edge case for full subspaces/zero holes (|2....2>), but the order you put the states and fragments in exposes the empty subspace first.

This is an interesting application that I hadn't thought of before. I worked on single-state vLASSCF first, and in a single state, subspaces like (0e,No) -> |0...0> and (2Ne,No) -> |2...2> don't make any sense because of their complete gauge invariance with the empty and inactive subspaces, respectively. (In other words, the energy of a single state is insensitive to how you partition totally-empty and totally-occupied orbitals into subspaces, and therefore, the "optimized" orbitals are arbitrary.) Therefore, I never bothered to test them. However, the state-average framework makes these states potentially interesting. I wonder if there is any gauge invariance in your setup.

At any rate, I'll take a look and see how easy it is to implement the full/empty edge cases. It might just be a few lines of code. If so, I'll probably put it on the dev branch, since this would be a new extension.

**Comment by MatthewRHermes** [comment]
Yeah sorry I got way ahead of myself without looking closely enough. The assertion is `nelec >= 0`; your quantum numbers work out to neleca,nelecb=0,-1 for one of the subspaces, which is the actual problem here. The full/empty edge cases actually don't throw an exception:

```
from pyscf import gto, scf, lib
from pyscf.tools import molden
from mrh.my_pyscf.mcscf.lasscf_testing import LASSCF

mol = gto.M (atom='Li 0 0 0; Na 3.0 0 0', basis='6-31g', output='LiNa_cas22_631g.log', verbose=lib.logger.INFO)
mf = scf.RHF (mol).run ()
molden.from_scf (mf, 'LiNa_hf_631g.molden')

las = LASSCF (mf, (1,1), (1,1)).state_average ([0.5,]*2,
    spins=[[0,0],[0,0]], smults=[[1,1],[1,1]], charges=[[1,-1],[-1,1]])
mo_loc = las.localize_init_guess ((list(range(1)),list(range(1,2))), mf.mo_coeff)
las.ah_level_shift=0.03
las.kernel (mo_loc)
print (las.e_states)
```

results in

```
overwrite output file: LiNa_cas22_631g.log
<class 'mrh.my_pyscf.fci.csf.FCISolver'> does not have attributes  charge
[-169.12546424 -169.27376921]
```

(there are clearly multiple local minima here; this was just a quick-and-dirty test)

**Comment by ruthenium96** [comment]
Thank you for your answers!
`# "Charges" should be self-explanatory`
This line of example code (mrh/examples/sa_si_lasscf/c2h4n4_631g.py) puts off my guard and I implicitly thought about valence state, Mulliken charges and so on. :)
In my understanding, one can sets the properties of LASSCF calculation using only `spins[i][j]` keys, am I right?

**Comment by MatthewRHermes** [comment]
You're right, that wasn't as self-explanatory as I thought. I modified it a little bit.
