### ISSUE TITLE
SOMF in LASSI

### ISSUE THREAD

**Issue by JangidBhavnesh** [MatthewRHermes/mrh#39]
When I am doing LASSI with one fragment and SOC = True, for a molecule with spin-multiplicity of 3, I should get 3 states  but here I am getting only one state?

Am I missing something?

# Sample input file
mol = struct(0, 0, '6-31g')
mol.spin = 2
mol.build()
mf = scf.RHF(mol).run()

las = LASSCF(mf, (6,), (6,), spin_sub=(3, ))
guess_mo = las.sort_mo([16,18,22,23,24,26])
mo0 = las.localize_init_guess([list(range (10)),],  guess_mo)
las.kernel(mo0)
e, si = las.lassi(opt=0, soc=True, break_symmetry=True)

**I think this has to multiplied with some density matrix (Probably 1TPDM) to get the splitting.**

**Comment by MatthewRHermes** [comment]
No, the issue is that you always get exactly as many states out as you put in. You need to build a model space before running the LASSI calculation. The sample code only builds one state in the model space, so you only get one energy back. If you want the triplet manifold, you need to build the M=0 and M=-1 states using state_average. Note that just the triplet manifold will not be affected by spin-orbit coupling in any way. To observe the effects of spin-orbit coupling, you need at minimum one singlet or one quintet state in addition to the triplet states.

**Comment by MatthewRHermes** [comment]
As a practical matter, note it is extremely difficult to find any main-group compound which is affected by spin-orbit coupling in any numerically substantial way. That is why my unittests are obliged to reduce the speed of light in order to test on meaningful numbers.

**Comment by JangidBhavnesh** [comment]
I understood that SOC is very minimalistic in main-group elements but for a triplet state I should get 3 states energy even if they are degenerate. Also I got you point that I have to create a model space to feed that LASSI function to get the right number of states

For above input file, this is working fine.
las = las.state_average([1,0, 0, 0], spins=[[0,],[2, ], [-2], [0, ]], smults=[[1,],[3,], [3,], [3,]], charges=[[0,],[0,], [0,], [0,]])

Is there a way to automatically create this model space?

**Comment by JangidBhavnesh** [comment]
Also, wouldn't it be nice to have a function to pass the eigen states of LASSI and respective S^2 values and SOMF integrals and that will give the SOC states. 

This might be the two-step approach instead of one-step approach implemented.
