### ISSUE TITLE
Question: fix_spin_ option in las

### ISSUE THREAD

**Issue by JangidBhavnesh** [MatthewRHermes/mrh#59]
Is there fix_spin_ option for individual fragment or overall in LASSCF?

**Comment by MatthewRHermes** [comment]
No because everything in LASSCF uses CSFs and therefore cannot normally break spin symmetry (except for the "RDMSolver" implementation, which abstracts the CI problem). If you mean LASSI, for dealing with the numerical noise that sometimes spoils the eigenvector spin symmetry, this is not implemented but it could be. It would take a bit of work.

**Comment by JangidBhavnesh** [comment]
Thanks.

Its clear now.
