### ISSUE TITLE
atol keyword unexpected

### ISSUE THREAD

**Issue by meaganoakley** [MatthewRHermes/mrh#6]
Hello, 

I am running a LASSCF computation with 9 fragments and a (4,4) active space on each fragment and I get this error: 

Overwritten attributes  get_hcore energy_nuc get_ovlp  of <class 'pyscf.scf.hf.RHF'>
Traceback (most recent call last):
  File "xxxx_las_9frag_44_df.py", line 168, in <module>
    energy_result = xxxx_dmet.doselfconsistent ()
  File "../../../mrh/my_dmet/main_object.py", line 536, in doselfconsistent
    u_diff, rdm = self.doselfconsistent_corrpot (rdm, [('corrpot', iteration)])
  File "../../../mrh/my_dmet/main_object.py", line 578, in doselfconsistent_corrpot
    orb_diff = self.doselfconsistent_orbs (lower_iters)
  File "../../../mrh/my_dmet/main_object.py", line 707, in doselfconsistent_orbs
    e_tot, grads = self.refragmentation (loc2wmas_new, loc2wmcs_new, oneRDM_loc)
  File "../../../mrh/my_dmet/main_object.py", line 856, in refragmentation
    e_tot, grads = self.lasci_(oneRDM_loc, loc2wmas=loc2wmas)
  File "../../../mrh/my_dmet/main_object.py", line 1448, in lasci_
    las, h2eff_sub, veff = self.lasci (dm0=dm0, loc2wmas=loc2wmas)
  File "../../../mrh/my_dmet/main_object.py", line 1439, in lasci
    e_tot, _, ci_sub, _, _, h2eff_sub, veff = las.kernel (mo_coeff = ao2no, ci0 = ci0, casdm0_sub = casdm0_sub)
  File "../../../mrh/my_pyscf/mcscf/lasci.py", line 637, in kernel
    kernel(self, mo_coeff, ci0=ci0, verbose=verbose, casdm0_sub=casdm0_sub, conv_tol_grad=conv_tol_grad)
  File "../../../mrh/my_pyscf/mcscf/lasci.py", line 361, in kernel
    callback=my_callback, M=prec_op)
TypeError: cg() got an unexpected keyword argument 'atol'

**Comment by MatthewRHermes** [comment]
Are you sure you're running in the correct environment?  (I.e., all required modules loaded.)  Very old versions of scipy didn't have the atol kwarg on the "cg" function, so that would have thrown that error.  But that would have killed every LASSCF calculation, and I know you've run at least one successfully to completion.  On the other hand I can reproduce that error if I try to call scipy.sparse.linalg.cg on the MSI login node (rather than Mesabi), because the version of scipy that gets shipped there is extremely old, but I'd be surprised if that was the first line that would give you a problem if that's what happened here.

Can you get into the same environment that you ran this calculation and tell me the scipy version?  Run "python" from the command line to start the interpreter, and then type

```
import scipy
print (scipy.__version__)
```

**Comment by meaganoakley** [comment]
I made sure to load newest python - not just the default on mesabi - and the error is gone. Thanks
