### ISSUE TITLE
Analysis of LASSI wavefunction not as expected

### ISSUE THREAD

**Issue by valay1** [MatthewRHermes/mrh#71]
For a TriIron system 
I am trying to analyze my LASSI wavefunction through the following snippet
```
from mrh.my_pyscf.lassi import states
from mrh.my_pyscf.mcscf.lasci import get_space_info
las=states.spin_shuffle(las)
las=states.all_single_excitations(las)
ncsf=las.get_ugg().ncsf_sub
charges, spins, smults, wfnsyms = get_space_info (las)
lroots=np.minimum(5,ncsf)
las.lasci()
las.lasci(lroots=lroots)
eroots,si=las.lassi()
from mrh.my_pyscf.lassi.sitools import analyze
ci1, si1, space_weights, navg, maxw, entr = analyze(las,si, state=[2,1,0,6,12,17,21,23],return_metrics=True)
np.save('r1_n5_ct/ci1',ci1)
np.save('r1_n5_ct/si1',si1)
```
and I get the error 
```
Traceback (most recent call last):
  File "/project/lgagliardi/valayagarawal/lasscf/mof_nodes/Fe_Fe_Fe/production/15_16/lassi.py", line 46, in <module>
    np.save('r1_n5_ct/ci1',ci1)
  File "/software/python-anaconda-2022.05-el8-x86_64/lib/python3.9/site-packages/numpy/lib/npyio.py", line 545, in save
    arr = np.asanyarray(arr)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 182) + inhomogeneous part.
```

How can I resolve this?

**Comment by MatthewRHermes** [comment]
The reason that las.ci is a list of list of ndarrays and not a larger-dimensional ndarray is that the length of the last three dimensions (lroots, ndeta, and ndetb) will generally differ from one fragment to another and from one rootspace to another, which can't be mapped to a single ndarray. `np.save` requires a single ndarray as input. You could iterate over the 3 fragments * 182 rootspaces and save them all separately, or you could use [h5py](https://docs.h5py.org/en/stable/quick.html#quick) instead of `np.save`, or you could flatten all the vectors and put metadata about how long each one is at the front, or you could just expand them all so that they are all the same size as the largest among them.
